name: covid-app
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.8
- conda
- scikit-learn
- scipy
- pandas
- numpy
- matplotlib
- fake_useragent
- pip
- pylint
- pydocstyle
- flake8
- black
- hvplot
- bokeh
- holoviews
- jupyter-server-proxy
- pip:
  - streamlit
  - streamlit-folium
